CREATE TABLE loot
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type             VARCHAR(31),
    name             VARCHAR(255),
    rarity           INTEGER,
    limited          BOOLEAN,
    splashart_card   BYTEA,
    splashart_banner BYTEA,
    media_id         BIGINT,
    description      VARCHAR(255),
    CONSTRAINT pk_loot PRIMARY KEY (id)
);

CREATE TABLE media
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    img  VARCHAR(255),
    CONSTRAINT pk_media PRIMARY KEY (id)
);

ALTER TABLE loot
    ADD CONSTRAINT FK_LOOT_ON_MEDIA FOREIGN KEY (media_id) REFERENCES media (id);