CREATE TABLE banner
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    limited_id   BIGINT,
    date_created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_banner PRIMARY KEY (id)
);

CREATE TABLE banner_loots
(
    Banner_id BIGINT NOT NULL,
    loots_id  BIGINT NOT NULL
);

ALTER TABLE banner
    ADD CONSTRAINT FK_BANNER_ON_LIMITED FOREIGN KEY (limited_id) REFERENCES loot (id);

ALTER TABLE banner_loots
    ADD CONSTRAINT fk_banloo_on_banner FOREIGN KEY (Banner_id) REFERENCES banner (id);

ALTER TABLE banner_loots
    ADD CONSTRAINT fk_banloo_on_loot FOREIGN KEY (loots_id) REFERENCES loot (id);